# Generated by Django 3.1.3 on 2020-11-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20201111_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='dacobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dacobjects', models.CharField(max_length=256, verbose_name='Модули')),
                ('modulehref', models.CharField(max_length=256, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
            },
        ),
        migrations.CreateModel(
            name='dacmatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceslevel', models.IntegerField(choices=[(1, 'Чтение'), (2, 'Редактирование'), (3, 'Редактирование и делегирование')], default=1, verbose_name='Уровень доступа')),
                ('dacobjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dacobj', to='menu.dacobj', verbose_name='Модули')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
