# Generated by Django 3.1.3 on 2020-11-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201111_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
    ]
