# Generated by Django 3.1.3 on 2020-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201111_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Почта'),
        ),
    ]
