# Generated by Django 3.1.3 on 2020-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201111_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='status',
            field=models.IntegerField(choices=[(1, 'Сотрудник'), (2, 'Клиент')], default=1, verbose_name='Роль'),
        ),
    ]
