# Generated by Django 3.1.3 on 2020-11-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201111_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Сотрудник'), (2, 'Клиент')], default=1, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
        ),
    ]
