# Generated by Django 3.1 on 2020-11-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201125_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='last_name',
        ),
    ]
