# Generated by Django 3.1 on 2020-12-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201126_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='last_name',
        ),
    ]
