# Generated by Django 3.1.3 on 2021-01-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201201_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='last_name',
        ),
    ]
