# Generated by Django 3.1.6 on 2021-02-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210202_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth',
            options={'ordering': ('-is_active',), 'verbose_name': 'Учетная запись', 'verbose_name_plural': 'Учетные записи'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-last_name',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
