# Generated by Django 3.1.3 on 2020-11-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_auto_20201111_1049'),
        ('users', '0002_auto_20201111_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=250, verbose_name='Задача')),
                ('Task_other', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('task_published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('task_compl', models.DateField(db_index=True, verbose_name='Дата выполнения')),
                ('task_status', models.BooleanField(null=0, verbose_name='Статус')),
                ('clientobj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='clients.clientobj', verbose_name='Объект')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.object_contracts', verbose_name='Договор')),
                ('userprof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-task_compl'],
            },
        ),
        migrations.CreateModel(
            name='Stask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stask_name', models.CharField(max_length=250, verbose_name='Подзадача')),
                ('stask_published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('stask_compl', models.DateField(db_index=True, verbose_name='Дата выполнения')),
                ('stask_status', models.BooleanField(null=0, verbose_name='Статус')),
                ('Task_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'ordering': ['-stask_compl'],
            },
        ),
    ]
