# Generated by Django 3.1.3 on 2020-11-17 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0005_auto_20201117_0932'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stask',
            old_name='Task_name',
            new_name='Task',
        ),
        migrations.AlterField(
            model_name='task',
            name='clientobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientobj', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='userprof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
