# Generated by Django 3.1.3 on 2020-11-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201117_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='stask_compl',
            field=models.DateTimeField(db_index=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_compl',
            field=models.DateTimeField(db_index=True, verbose_name='Дата выполнения'),
        ),
    ]
