# Generated by Django 3.1.3 on 2020-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201118_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_start',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала задачи'),
        ),
    ]
