# Generated by Django 3.1.3 on 2020-11-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='clientobj',
        ),
    ]
