# Generated by Django 3.1.3 on 2020-12-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_clientobj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача'),
        ),
        migrations.CreateModel(
            name='Stask_foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='report_images', verbose_name='Изображения')),
                ('Stask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.stask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения подзадач',
            },
        ),
    ]
