# Generated by Django 3.1.4 on 2020-12-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201201_0920'),
        ('tasks', '0006_auto_20201206_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='userprof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Сотрудник'),
        ),
    ]
