# Generated by Django 3.1.4 on 2020-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20201210_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='stask',
            name='Stask_other',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
