# Generated by Django 3.1.3 on 2021-01-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201210_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stask_foto',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Фотоотчет подзадач'},
        ),
    ]
