# Generated by Django 3.1.3 on 2021-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210107_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask_foto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='report_images', verbose_name='Изображения'),
        ),
    ]
