# Generated by Django 3.1.3 on 2021-01-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210111_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglament_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.CharField(max_length=250, verbose_name='Подзадача')),
            ],
            options={
                'verbose_name': 'Категория регламентных работ',
                'verbose_name_plural': 'Категории регламентных работ',
            },
        ),
        migrations.CreateModel(
            name='Reglament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=250, verbose_name='Вид работы')),
                ('Task_period', models.IntegerField(choices=[(1, 'Ежедневно'), (2, 'Еженедельно'), (3, 'Ежемесячно'), (4, 'Ежеквартально'), (5, 'Ежегодно'), (6, 'Другое')], default=3, verbose_name='Переодичность')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.reglament_cat', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Регламентная работа',
                'verbose_name_plural': 'Регламентные работы',
                'ordering': ['-cat'],
            },
        ),
    ]
