# Generated by Django 3.1.3 on 2021-01-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_reglament_reglament_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='trasfer_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.task', verbose_name='Задача')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to', to=settings.AUTH_USER_MODEL, verbose_name='Кому перенос')),
            ],
            options={
                'verbose_name': 'Уведомление о переносе',
                'verbose_name_plural': 'Уведомления о переносе',
            },
        ),
    ]
