# Generated by Django 3.1.3 on 2021-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_trasfer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglament',
            name='Task_period',
            field=models.IntegerField(choices=[(1, 'Ежедневно'), (2, 'Еженедельно'), (3, 'Ежемесячно'), (4, 'Раз в полгода'), (5, 'Ежегодно'), (6, 'Другое')], default=3, verbose_name='Переодичность'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=0, verbose_name='Статус'),
        ),
    ]
