# Generated by Django 3.1.3 on 2021-02-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20210127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglament',
            name='Task_period',
            field=models.IntegerField(choices=[(1, 'Сезонные'), (2, 'Ежеквартально'), (3, 'Ежемесячно'), (4, 'Раз в полгода'), (5, 'Ежегодно'), (6, 'Другое')], default=3, verbose_name='Переодичность'),
        ),
    ]
