# Generated by Django 3.1.3 on 2020-11-11 09:22

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=250, null=True, verbose_name='Объект')),
                ('object_adress', models.CharField(max_length=250, null=True, verbose_name='Адрес')),
                ('object_telephone', models.CharField(max_length=250, null=True, verbose_name='Телефон')),
                ('object_email', models.CharField(max_length=250, null=True, verbose_name='Почта')),
                ('object_site', models.CharField(max_length=250, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250, verbose_name='Краткое наименование')),
                ('client_fullname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Полное наименование')),
                ('client_inn', models.CharField(blank=True, max_length=250, null=True, verbose_name='ИНН')),
                ('client_ogrn', models.CharField(blank=True, max_length=250, null=True, verbose_name='ОГРН')),
                ('client_kpp', models.CharField(blank=True, max_length=250, null=True, verbose_name='КПП')),
                ('client_factaddr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фактический адрес')),
                ('client_juraddr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Юридический адрес')),
                ('client_telephone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('client_mail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Почта')),
                ('client_site', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['client_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='object_contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_contracts', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Договор')),
                ('clientobj', models.ManyToManyField(to='clients.clientobj', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(null=True, upload_to='docs/')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='contact_man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=250, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность')),
                ('company', models.CharField(blank=True, max_length=250, null=True, verbose_name='Компания')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Почта')),
                ('telephone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
            },
        ),
    ]
