# Generated by Django 3.1.3 on 2020-11-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201111_0922'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clients',
            managers=[
            ],
        ),
    ]
