# Generated by Django 3.1.3 on 2020-11-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20201117_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object_contracts',
            name='clientobj',
        ),
        migrations.AddField(
            model_name='object_contracts',
            name='clientobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientobj', verbose_name='Объект'),
        ),
    ]
