# Generated by Django 3.1.3 on 2020-11-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20201118_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object_contracts',
            name='clientobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientobj', to='clients.clientobj', verbose_name='Объект'),
        ),
    ]
