# Generated by Django 3.1 on 2020-12-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20201125_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='object_contracts',
            name='contracts_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='object_contracts',
            name='contracts_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование'),
        ),
    ]
