# Generated by Django 3.1.4 on 2020-12-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20201201_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object_contracts',
            name='clientobj',
        ),
        migrations.AddField(
            model_name='object_contracts',
            name='clientobj',
            field=models.ManyToManyField(related_name='clientobj', to='clients.clientobj', verbose_name='Объект'),
        ),
    ]
