# Generated by Django 3.1.4 on 2020-12-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20201215_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object_contracts',
            name='clientobj',
        ),
        migrations.AddField(
            model_name='object_contracts',
            name='clientobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientobj', to='clients.clientobj', verbose_name='Объект'),
        ),
    ]
