# Generated by Django 3.1.3 on 2021-01-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_auto_20201201_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, verbose_name='Дата начала отпуска')),
                ('end', models.DateField(db_index=True, verbose_name='Дата окончания отпуска')),
                ('unit', models.CharField(blank=True, choices=[(1, 'Административный отдел'), (2, 'Технический отдел - инженера'), (3, 'Технический отдел - Монтажники'), (4, 'Отдел продаж')], default=1, max_length=250, null=True, verbose_name='Отдел')),
                ('userprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
            },
        ),
    ]
