# Generated by Django 3.1.3 on 2021-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(1, 'Административный отдел'), (2, 'Технический отдел - инженера'), (3, 'Технический отдел - Монтажники'), (4, 'Отдел продаж')], default=1, null=True, verbose_name='Отдел'),
        ),
    ]
