# Generated by Django 3.1.3 on 2021-01-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_auto_20210115_0936'),
        ('vacations', '0002_auto_20210119_0824'),
    ]

    operations = [
    ]
