# Generated by Django 3.1.3 on 2020-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=250, verbose_name='Задача')),
                ('Task_other', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('task_published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('task_compl', models.DateTimeField(db_index=True, verbose_name='Дата выполнения')),
                ('task_status', models.BooleanField(null=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-task_compl'],
            },
        ),
    ]
