# Generated by Django 3.1.3 on 2021-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_compl',
            field=models.DateField(db_index=True, verbose_name='Дата выполнения'),
        ),
    ]
