# Generated by Django 3.1.3 on 2021-01-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_remove_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checklist.company', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
