# Generated by Django 3.1.3 on 2021-01-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_task_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.company', verbose_name='Организация'),
        ),
    ]
